spring.application.name=demo
spring.jackson.deserialization.fail-on-null-for-primitives=false

# API externa que se va a consumir para el catálogo de productos
app.dummyjson.base-url=https://dummyjson.com

# Conexión a PostgreSQL local
spring.datasource.url=jdbc:postgresql://localhost:5432/webii_tp2
spring.datasource.username=webii_tp2
spring.datasource.password=webii_tp2

# Hibernate y control del esquema
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

